### ISSUE TITLE
High memory usage on windows machines

### ISSUE THREAD

**Issue by sniperadmin** [blnqco/blnq-studio#7]
### Bug Details
---
After 10 minutes of working on the editor, Memory started to BOOM 💣 🔥 

Before closing editor (screenshot)
![image](https://user-images.githubusercontent.com/24525973/93687179-01d8c300-fabc-11ea-96c7-3f007e0a18fc.png)

After closing editor (screenshot)
![image](https://user-images.githubusercontent.com/24525973/93687189-11580c00-fabc-11ea-9719-9f75012cf628.png)

I really like the app, but this is a really big issue!
@nicferrier - @lleighton - @davidyarham - @contractor-blnq

**Comment by davidyarham** [comment]
Sorry for the delay in seeing this, will take a look.

**Comment by lleighton** [comment]
Hi @sniperadmin would you mind trying running in chrome with plugins disabled?

**Comment by sniperadmin** [comment]
Hi @davidyarham  & @lleighton 
thanks for the response :) I will try on chrome

**Comment by sniperadmin** [comment]
so far, so good then!
so it works on chrome with plugins disabled..

May i ask about the lighthouse testing there? performance becomes lower than 60% once importing a css framework. Code splitting does not fix that.. i thought of using bundlers, but not sure if they are supported?

**Comment by lleighton** [comment]
It's probably down the frameworks size.

Code splitting and bundling options are your best shot.
